base:
  - ../../common/refsrwkv.yaml
  - ../../models/refsr/refsrwkv.yaml
  - ../../common/benchmark.yaml

dataset:
  config: ../../datasets/refsr/hrms_scd.yaml

run:
  name: hrms_scd_sr_x4
  scale: 4
  lr_patch: 48

data:
  reference_mode: none
  max_samples_val: 300

model:
  use_reference: false

loss:
  ssim_weight: 0.0
  fft_weight: 0.0
