base:
  - ../../common/refsrwkv.yaml
  - ../../models/refsr/refsrwkv.yaml

dataset:
  config: ../../datasets/sr/ucmerced.yaml

run:
  name: ucmerced_x4
  scale: 4
  lr_patch: 48

data:
  reference_mode: lr_up
  val_batch_size: 1
  max_samples_val: 300
