base:
  - ../../../common/refsr_paired.yaml
  - ../../../models/refsr/masa_sr.yaml
  - ../../../common/benchmark.yaml

dataset:
  config: ../../../datasets/refsr/hrms_scd.yaml

run:
  name: hrms_scd_masa_sr_x4
  scale: 4
  lr_patch: 48

data:
  max_samples_val: 300
