"""Configuration loading for the task/model/data split.

Run YAML files are intentionally small.  They may inherit one or more base
files, refer to a dataset description, and override any value from the
command line with ``section.key=value``.  Once a run has an editable
``experiments/.../config.yaml`` snapshot, layered run paths prefer that file.
The loader returns one materialized mapping consumed by training and
evaluation entry points.
"""

from __future__ import annotations

import copy
import os
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from .common import PROJECT_ROOT, deep_merge, resolve_path


_REFERENCE_MODE_ALIASES = {
    "paired": "paired",
    "lr": "lr_up",
    "lr_up": "lr_up",
    "sisr": "lr_up",
    "bicubic_lr": "lr_up",
}
_LR_SOURCE_ALIASES = {
    "auto": "auto",
    "stored": "stored",
    "disk": "stored",
    "from_hr": "from_hr",
    "hr": "from_hr",
    "generated": "from_hr",
}
_LR_PROVENANCE_ALIASES = {
    "bicubic": "bicubic",
    "synthetic": "bicubic",
    "downsampled": "bicubic",
    "sensor": "sensor",
    "measured": "sensor",
    "real": "sensor",
}
_PAIRED_ONLY_DATA_KEYS = (
    "augment_ref",
    "ref_aug_strengths",
    "ref_aug_probs",
    "ref_gray_prob",
)
_PAIRED_ONLY_LOSS_KEYS = ("ref_drop_prob",)

# Direct RefSR models all expose ``forward(lr, ref)``.  Keeping the names in
# runtime (rather than importing model packages here) lets config rendering,
# training and evaluation agree on the task without pulling optional model
# dependencies into the configuration parser.
DIRECT_REFSR_MODEL_NAMES = frozenset({"refsrwkv", "ttsr", "masa_sr", "datsr"})
REFSR_MODEL_NAMES = DIRECT_REFSR_MODEL_NAMES | frozenset({"refdiffrwkv"})
PAIRED_REFERENCE_MODEL_NAMES = frozenset({"ttsr", "masa_sr", "datsr", "refdiffrwkv"})


def normalize_reference_mode(value: Any) -> str:
    """Return the canonical RefSR reference source mode.

    ``paired`` consumes an on-disk ``Ref/`` image.  ``lr_up`` is the SISR
    fallback used by direct RefSR models on HR/LR-only datasets: its reference
    is generated by bicubic upsampling the current LR image at runtime.
    """
    normalized = str(value).strip().lower()
    try:
        return _REFERENCE_MODE_ALIASES[normalized]
    except KeyError as exc:
        options = ", ".join(sorted({"paired", "lr_up"}))
        raise ValueError(f"data.reference_mode 必须是 {options}，得到 {value!r}") from exc


def normalize_lr_source(value: Any) -> str:
    """Return the canonical source policy for the LR tensor."""
    normalized = str(value).strip().lower()
    try:
        return _LR_SOURCE_ALIASES[normalized]
    except KeyError as exc:
        options = ", ".join(sorted({"auto", "stored", "from_hr"}))
        raise ValueError(f"data.lr_source 必须是 {options}，得到 {value!r}") from exc


def normalize_lr_provenance(value: Any) -> str:
    """Return ``bicubic`` for synthetic LR or ``sensor`` for measurements."""
    normalized = str(value).strip().lower()
    try:
        return _LR_PROVENANCE_ALIASES[normalized]
    except KeyError as exc:
        options = ", ".join(sorted({"bicubic", "sensor"}))
        raise ValueError(f"data.lr_provenance 必须是 {options}，得到 {value!r}") from exc


def is_refsr_model(value: Any) -> bool:
    """Return whether a registered model name belongs to the RefSR task."""
    return str(value or "").strip().lower() in REFSR_MODEL_NAMES


def validate_refsr_reference_contract(config: Mapping[str, Any]) -> None:
    """Reject RefSR configurations whose reference settings cannot take effect.

    Keeping this rule at the configuration boundary prevents a common silent
    error: a HR/LR-only run inherited color/style augmentation meant for a
    physical reference image.  RefDiffRWKV deliberately remains paired-only
    because its training system consumes ``batch['ref']`` directly.
    """
    data = config.get("data", {})
    model = config.get("model", {})
    if not isinstance(data, Mapping) or not isinstance(model, Mapping):
        return

    model_name = str(model.get("name") or model.get("id") or "").strip().lower()
    task = str(config.get("task") or "").strip().lower()
    is_refsr = task == "refsr" or is_refsr_model(model_name)
    if not is_refsr:
        return

    mode = normalize_reference_mode(data.get("reference_mode", "paired"))
    if model_name in PAIRED_REFERENCE_MODEL_NAMES and mode != "paired":
        if model_name == "refdiffrwkv":
            detail = "训练和推理都需要真实的 LR/HR/Ref 三元组。"
        else:
            detail = "该比较基线只能使用真实的 LR/HR/Ref 三元组。"
        raise ValueError(
            f"model.name={model.get('name', model_name)} 当前只支持 "
            f"data.reference_mode=paired；{detail}"
        )
    if mode != "lr_up":
        return

    invalid = [f"data.{key}" for key in _PAIRED_ONLY_DATA_KEYS if key in data]
    loss = config.get("loss", {})
    if isinstance(loss, Mapping):
        invalid.extend(f"loss.{key}" for key in _PAIRED_ONLY_LOSS_KEYS if key in loss)
    if invalid:
        raise ValueError(
            "data.reference_mode=lr_up 从 LR 动态生成自参考，不能配置只对真实 Ref "
            f"生效的字段: {', '.join(invalid)}。请删除这些字段，或改用 paired 数据集。"
        )


def load_yaml_file(path: str | os.PathLike[str], stack: tuple[Path, ...] = ()) -> dict[str, Any]:
    """Read a YAML file and recursively merge its ``base`` references."""
    resolved = Path(path).expanduser()
    if not resolved.is_absolute():
        resolved = (Path.cwd() / resolved) if (Path.cwd() / resolved).is_file() else PROJECT_ROOT / resolved
    resolved = resolved.resolve()
    if resolved in stack:
        chain = " -> ".join(str(item) for item in (*stack, resolved))
        raise ValueError(f"配置 base 循环引用: {chain}")
    if not resolved.is_file():
        raise FileNotFoundError(f"配置文件不存在: {resolved}")
    with resolved.open("r", encoding="utf-8-sig") as handle:
        value = yaml.safe_load(handle) or {}
    if not isinstance(value, dict):
        raise ValueError(f"配置文件顶层必须是 mapping: {resolved}")
    value = copy.deepcopy(value)
    bases = value.pop("base", None)
    if bases is None:
        return value
    if isinstance(bases, (str, os.PathLike)):
        bases = [bases]
    if not isinstance(bases, (list, tuple)):
        raise ValueError(f"配置 base 必须是路径或路径列表: {resolved}")
    merged: dict[str, Any] = {}
    for reference in bases:
        base_path = Path(reference).expanduser()
        if not base_path.is_absolute():
            base_path = resolved.parent / base_path
        merged = deep_merge(merged, load_yaml_file(base_path, (*stack, resolved)))
    return deep_merge(merged, value)


def apply_overrides(config: dict[str, Any], overrides: list[str] | None = None) -> dict[str, Any]:
    """Apply dotted ``key=value`` overrides using YAML scalar parsing."""
    result = copy.deepcopy(config)
    for item in overrides or []:
        if "=" not in item:
            raise ValueError(f"--overrides 项缺少 = : {item!r}")
        key, raw = item.split("=", 1)
        parts = [part.strip() for part in key.split(".")]
        if not parts or any(not part for part in parts):
            raise ValueError(f"--overrides 键无效: {item!r}")
        try:
            value = yaml.safe_load(raw)
        except yaml.YAMLError:
            value = raw
        node: dict[str, Any] = result
        for part in parts[:-1]:
            if not isinstance(node.get(part), dict):
                node[part] = {}
            node = node[part]
        node[parts[-1]] = value
    return result


def _dataset_spec(config: dict[str, Any], config_path: Path) -> dict[str, Any]:
    raw = config.get("dataset", {})
    if isinstance(raw, str):
        raw = {"id": raw}
    if not isinstance(raw, dict):
        raise ValueError("dataset 必须是 mapping、名称或配置路径")

    reference = raw.get("config") or raw.get("ref")
    if reference:
        ref_path = Path(reference).expanduser()
        if not ref_path.is_absolute():
            ref_path = config_path.parent / ref_path
        referenced = load_yaml_file(ref_path)
        referenced = referenced.get("dataset", referenced)
        if not isinstance(referenced, dict):
            raise ValueError(f"数据集配置没有 dataset mapping: {ref_path}")
        local = {key: value for key, value in raw.items() if key not in {"config", "ref"}}
        return deep_merge(referenced, local)

    dataset_id = raw.get("id")
    if dataset_id and not raw.get("root"):
        candidates = [
            PROJECT_ROOT / "configs" / "datasets" / f"{dataset_id}.yaml",
            PROJECT_ROOT / "configs" / "datasets" / "sr" / f"{dataset_id}.yaml",
            PROJECT_ROOT / "configs" / "datasets" / "refsr" / f"{dataset_id}.yaml",
        ]
        for candidate in candidates:
            if candidate.is_file() and candidate.resolve() != config_path.resolve():
                referenced = load_yaml_file(candidate).get("dataset", {})
                if isinstance(referenced, dict):
                    return deep_merge(referenced, raw)
    return raw


def _slug(value: Any, fallback: str) -> str:
    text = str(value or fallback).strip().replace("\\", "_").replace("/", "_")
    return text or fallback


def materialize_config(config: dict[str, Any], config_path: Path) -> dict[str, Any]:
    """Fill the common task/data/model/output fields without model imports."""
    result = copy.deepcopy(config)
    dataset = _dataset_spec(result, config_path)
    for section_name in ("run", "data", "model", "train", "loss", "output"):
        section = result.setdefault(section_name, {})
        if not isinstance(section, dict):
            raise ValueError(f"{section_name} 必须是 mapping")

    model = result["model"]
    data = result["data"]
    run = result["run"]
    train = result["train"]
    output = result["output"]
    dataset_id = _slug(dataset.get("id"), "dataset")
    model_name = _slug(model.get("name") or model.get("id"), config_path.parent.name)

    task = str(result.get("task") or model.get("task") or "").lower().strip()
    if task not in {"sr", "refsr"}:
        task = "refsr" if is_refsr_model(model_name) else "sr"
    result["task"] = task
    model["name"] = model_name

    root = data.get("root") or run.get("data_root") or dataset.get("root")
    if root:
        data["root"] = root
    scale = run.get("scale", data.get("scale", dataset.get("default_scale")))
    if scale is not None:
        if isinstance(scale, bool) or not isinstance(scale, int) or scale < 1:
            raise ValueError(f"scale 必须是正整数，得到 {scale!r}")
        data["scale"] = int(scale)
        run["scale"] = int(scale)

    # Dataset descriptions carry the physical LR facts.  Materialize them in
    # ``data`` so loaders and saved config snapshots remain self-contained.
    dataset_lr = dataset.get("lr", {})
    data_lr = data.get("lr", {})
    if not isinstance(dataset_lr, Mapping):
        dataset_lr = {}
    if not isinstance(data_lr, Mapping):
        data_lr = {}
    data.setdefault(
        "lr_native_scale",
        data_lr.get("native_scale", dataset_lr.get("native_scale", dataset.get("default_scale", data.get("scale")))),
    )
    data.setdefault(
        "lr_provenance",
        data_lr.get("provenance", dataset_lr.get("provenance", dataset.get("lr_provenance", "bicubic"))),
    )
    data.setdefault(
        "lr_source",
        data_lr.get("source", dataset_lr.get("source", dataset.get("lr_source", "auto"))),
    )
    # Physical resolution metadata is distinct from the integer tensor scale.
    # Wuhan TIFFs are already on a common pixel grid (tensor scale x1) while
    # ERGAS still needs the real 30 m / 8 m ratio.
    if "physical_resolution_ratio" in dataset and "physical_resolution_ratio" not in data:
        data["physical_resolution_ratio"] = dataset["physical_resolution_ratio"]
    if "format" in dataset and "dataset_format" not in data:
        data["dataset_format"] = dataset["format"]
    if "kind" in dataset and "dataset_kind" not in data:
        data["dataset_kind"] = dataset["kind"]
    if isinstance(dataset.get("source"), Mapping):
        source = dataset["source"]
        if "channels" in source and "channels" not in data:
            data["channels"] = source["channels"]
        if "normalization" in source and "normalization" not in data:
            data["normalization"] = source["normalization"]
    data["lr_source"] = normalize_lr_source(data.get("lr_source", "auto"))
    data["lr_provenance"] = normalize_lr_provenance(
        data.get("lr_provenance", "bicubic")
    )
    if data.get("lr_native_scale") is not None:
        native_scale = data["lr_native_scale"]
        if isinstance(native_scale, bool) or not isinstance(native_scale, int) or native_scale < 1:
            raise ValueError("data.lr_native_scale 必须是正整数")

    lr_patch = run.get("lr_patch", data.get("train_lr_patch"))
    if lr_patch is not None:
        if isinstance(lr_patch, bool) or not isinstance(lr_patch, int) or lr_patch < 1:
            raise ValueError(f"run.lr_patch 必须是正整数，得到 {lr_patch!r}")
        data["train_lr_patch"] = int(lr_patch)
        if scale is not None:
            data["train_hr_patch"] = int(lr_patch) * int(scale)
            data.setdefault("patch_size", data["train_hr_patch"])

    if task == "refsr":
        dataset_kind = str(dataset.get("kind", "")).strip().lower()
        dataset_identifier = str(dataset.get("id", "")).strip().lower()
        default_reference_mode = (
            "paired"
            if dataset_kind == "paired_reference"
            or "wuhan" in dataset_kind
            or "wuhan" in dataset_identifier
            else "lr_up"
        )
        data["reference_mode"] = normalize_reference_mode(
            data.get("reference_mode", default_reference_mode)
        )
    data.setdefault("lr_key", model.get("lr_key", "lr"))
    data.setdefault("hr_key", model.get("hr_key", "hr"))
    data.setdefault("ref_key", model.get("ref_key", "ref"))
    data.setdefault("max_samples_train", None)
    data.setdefault("max_samples_val", None)
    data.setdefault("max_samples_test", None)
    data.setdefault("pin_memory", True)

    run_name = _slug(run.get("name") or output.get("experiment_name"), f"{dataset_id}_x{scale or 'native'}")
    run["name"] = run_name
    output.setdefault("root", "experiments")
    output.setdefault("train_root", str(Path(output["root"]) / "train"))
    output.setdefault("test_root", str(Path(output["root"]) / "test"))
    output.setdefault("experiment_name", run_name)
    output.setdefault("checkpoint_dir", str(Path(output["train_root"]) / task / model_name / dataset_id / f"x{scale or 'native'}" / run_name / "checkpoints"))
    output.setdefault("log_dir", str(Path(output["train_root"]) / task / model_name / dataset_id / f"x{scale or 'native'}" / run_name / "logs"))
    output.setdefault("test_dir", str(Path(output["test_root"]) / task / model_name / dataset_id / f"x{scale or 'native'}" / run_name))
    result["dataset"] = dataset
    result["_config_path"] = str(config_path.resolve())
    return result


def _is_run_config(path: Path) -> bool:
    """Return whether ``path`` is one of the repository's layered run files."""
    try:
        path.relative_to(PROJECT_ROOT / "configs" / "runs")
    except ValueError:
        return False
    return True


def _existing_experiment_config(config: dict[str, Any], config_path: Path) -> Path | None:
    """Find the materialized config for a layered run when it already exists."""
    if not _is_run_config(config_path):
        return None

    # Import lazily to keep the configuration module independent from the
    # experiment path implementation during module import.
    from .experiments import layout_from_config

    candidate = layout_from_config(config).train_dir / "config.yaml"
    if candidate.resolve() == config_path.resolve() or not candidate.is_file():
        return None
    return candidate


def load_config(
    path: str | os.PathLike[str],
    overrides: list[str] | None = None,
    *,
    prefer_existing: bool = True,
) -> dict[str, Any]:
    """Load a config, preferring an existing run snapshot for layered runs.

    A path under ``configs/runs`` first determines its materialized experiment
    directory.  If that directory already contains ``config.yaml``, the
    snapshot is loaded instead, so shortcut commands reuse manual edits.  A
    direct path to a complete YAML is always honored; pass
    ``prefer_existing=False`` when rendering a fresh snapshot from defaults.
    """
    config_path = resolve_path(path, prefer_cwd=True)
    source = apply_overrides(load_yaml_file(config_path), overrides)
    materialized = materialize_config(source, config_path)
    if prefer_existing:
        existing = _existing_experiment_config(materialized, config_path)
        if existing is not None:
            config_path = existing
            source = apply_overrides(load_yaml_file(config_path), overrides)
    return materialize_config(source, config_path)


def load_test_yaml(
    path: str | os.PathLike[str], overrides: list[str] | None = None
) -> tuple[dict[str, Any], Path]:
    """Load a standalone evaluation YAML without resolving a training run.

    Test YAMLs intentionally contain only evaluation policy (the ``test``
    mapping).  Model, dataset, and architecture settings are supplied by the
    checkpoint's embedded ``trainer_config`` instead of being re-read from a
    file under ``configs/runs``.
    """
    config_path = resolve_path(path, prefer_cwd=True)
    source = apply_overrides(load_yaml_file(config_path), overrides)
    test = source.get("test")
    if not isinstance(test, Mapping):
        raise ValueError(
            f"独立测试配置必须包含 test mapping: {config_path}"
        )
    return source, config_path


def merge_test_policy(
    training_config: Mapping[str, Any],
    test_config: Mapping[str, Any],
    *,
    test_config_path: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Overlay an independent test policy onto a complete training config."""
    if not isinstance(training_config, Mapping) or not training_config:
        raise ValueError("训练配置必须是非空 mapping")
    if not isinstance(test_config, Mapping) or not isinstance(test_config.get("test"), Mapping):
        raise ValueError("独立测试配置必须包含 test mapping")
    # The standalone test policy is authoritative as a whole.  Replacing the
    # section (instead of recursively merging it) prevents stale fields such
    # as an old ``test.split`` in the training checkpoint from overriding the
    # current ``test.splits`` setting.
    merged = deep_merge(dict(training_config), dict(test_config))
    test = copy.deepcopy(dict(test_config["test"]))
    merged["test"] = test
    if not isinstance(test, dict):
        raise ValueError("test 必须是 mapping")
    test.setdefault("splits", ["test"])
    test.setdefault("metrics", ["psnr", "ssim"])
    test.setdefault("save_images", True)
    test.setdefault("device", None)
    test.setdefault("batch_size", None)
    test.setdefault("steps", None)
    test.setdefault("output", None)
    if test_config_path is not None:
        merged["_test_config_path"] = str(Path(test_config_path).resolve())
    return merged


def merge_test_config(
    test_config: Mapping[str, Any],
    checkpoint: Any,
    *,
    test_config_path: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Overlay an independent test policy onto a checkpoint configuration."""
    from .checkpoint import checkpoint_config, load_checkpoint

    if isinstance(checkpoint, (str, os.PathLike)):
        checkpoint = load_checkpoint(checkpoint)
    training_config = checkpoint_config(checkpoint)
    if not training_config:
        raise ValueError(
            "checkpoint 不包含 trainer_config；请使用保存了最终训练 YAML 的 checkpoint"
        )
    return merge_test_policy(
        training_config,
        test_config,
        test_config_path=test_config_path,
    )


def load_test_config(
    path: str | os.PathLike[str],
    checkpoint: Any,
    overrides: list[str] | None = None,
) -> dict[str, Any]:
    """Load an independent test YAML and merge it with checkpoint metadata."""
    source, config_path = load_test_yaml(path, overrides)
    return merge_test_config(source, checkpoint, test_config_path=config_path)


def validate_config(config: dict[str, Any], *, require_data: bool = True) -> None:
    """Validate fields shared by all native loaders and Lightning runners."""
    for section in ("data", "model", "train", "loss", "output", "test"):
        if section in config and not isinstance(config[section], dict):
            raise ValueError(f"{section} 必须是 mapping")
    data, model = config.get("data", {}), config.get("model", {})
    test = config.get("test", {})
    if test and isinstance(test, Mapping):
        splits = test.get("split", test.get("splits", ["test"]))
        if isinstance(splits, str):
            splits = [splits]
        if not isinstance(splits, (list, tuple)) or not splits or any(str(split) not in {"test", "test_easy", "test_hard"} for split in splits):
            raise ValueError("test.splits 必须是 test、test_easy、test_hard 的非空列表")
        save_images = test.get("save_images", True)
        if not isinstance(save_images, bool):
            raise ValueError("test.save_images 必须是布尔值")
    elif test:
        raise ValueError("test 必须是 mapping")
    if require_data:
        if not data.get("root"):
            raise ValueError("data.root 未设置")
        if not isinstance(data.get("scale"), int) or data["scale"] < 1:
            raise ValueError("data.scale 必须是正整数")
        nested_lr = data.get("lr", {})
        if not isinstance(nested_lr, Mapping):
            nested_lr = {}
        lr_source = normalize_lr_source(
            data.get("lr_source", nested_lr.get("source", "auto"))
        )
        lr_provenance = normalize_lr_provenance(
            data.get("lr_provenance", nested_lr.get("provenance", "bicubic"))
        )
        native_scale = data.get(
            "lr_native_scale", nested_lr.get("native_scale", data["scale"])
        )
        if isinstance(native_scale, bool) or not isinstance(native_scale, int) or native_scale < 1:
            raise ValueError("data.lr_native_scale 必须是正整数")
        if lr_provenance == "sensor":
            if lr_source == "from_hr":
                raise ValueError("sensor LR 不能设置 data.lr_source=from_hr")
            if native_scale != data["scale"]:
                raise ValueError(
                    "sensor LR 只能使用原生倍率: "
                    f"native=x{native_scale}, requested=x{data['scale']}"
                )
        if "physical_resolution_ratio" in data:
            ratio = data["physical_resolution_ratio"]
            if isinstance(ratio, bool) or not isinstance(ratio, (int, float)) or ratio <= 0:
                raise ValueError("data.physical_resolution_ratio 必须是正数")
        dataset_info = config.get("dataset", {})
        if not isinstance(dataset_info, Mapping):
            dataset_info = {}
        wuhan_markers = {
            str(value).strip().lower()
            for value in (
                dataset_info.get("id"),
                dataset_info.get("kind"),
                data.get("dataset_format"),
                data.get("dataset_kind"),
                data.get("format"),
                str(data.get("root", "")).split("/")[-1],
            )
            if value is not None
        }
        if any("wuhan" in marker for marker in wuhan_markers):
            if data["scale"] != 1:
                raise ValueError(
                    "Wuhan TIFF 已在同一像素网格对齐，data.scale 必须为 1；"
                    "30/8=3.75 只用于 ERGAS"
                )
            if data.get("reference_mode", "paired") != "paired":
                raise ValueError("Wuhan RefSR 必须使用 data.reference_mode=paired")
            if data.get("channels", 4) != 4:
                raise ValueError("Wuhan TIFF 数据必须是 4 通道")
            if "value_scale" in data:
                value_scale = data["value_scale"]
                if isinstance(value_scale, bool) or not isinstance(value_scale, (int, float)) or value_scale <= 0:
                    raise ValueError("data.value_scale 必须是正数")
            for field in ("inp_channels", "out_channels", "ref_channels"):
                if field in model and model[field] != 4:
                    raise ValueError(f"Wuhan 四通道模型要求 model.{field}=4")
    if not str(model.get("name", "")).strip():
        raise ValueError("model.name 必须是非空字符串")
    validate_refsr_reference_contract(config)
    for key, default in (("batch_size", 1), ("val_batch_size", 1), ("num_workers", 0), ("val_num_workers", 0)):
        value = data.get(key, default)
        minimum = 0 if "workers" in key else 1
        if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
            raise ValueError(f"data.{key} 必须是 >= {minimum} 的整数")
    train = config.get("train", {})
    for key in ("learning_rate", "weight_decay", "lr_factor", "lr_min", "ema_decay"):
        if key in train and not isinstance(train[key], (int, float)):
            raise ValueError(f"train.{key} 必须是数值")


__all__ = [
    "apply_overrides",
    "DIRECT_REFSR_MODEL_NAMES",
    "load_config",
    "load_test_config",
    "load_test_yaml",
    "load_yaml_file",
    "merge_test_config",
    "merge_test_policy",
    "materialize_config",
    "PAIRED_REFERENCE_MODEL_NAMES",
    "REFSR_MODEL_NAMES",
    "is_refsr_model",
    "normalize_reference_mode",
    "normalize_lr_source",
    "normalize_lr_provenance",
    "validate_config",
    "validate_refsr_reference_contract",
]
