base:
  - ../../../common/sr.yaml
  - ../../../models/sr/swinir_m.yaml

dataset:
  config: ../../../datasets/refsr/hrms_scd.yaml

run:
  name: hrms_scd_swinir_x4
  scale: 4
  lr_patch: 48

data:
  max_samples_val: 300

train:
  learning_rate: 1.0e-4
  lr_scheduler: plateau
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

loss:
  name: l1
