# configs/light_train_config.yaml
# python scripts/train.py --config configs/light_train_config.yaml

# 模型参数
# ========== RefDiffRWKV 参数（主扩散模型） ==========
model:
  img_size: 256
  patch_size: 4
  embed_dim: 48
  channels: 3
  enc_blocks: [4, 6, 6]
  dec_blocks: [6, 6, 4]
  latent_blocks: 8
  drop_path_rate: 0.1
  hidden_rate: 4
  learn_sigma: false
  upsample_mode: "cnn"

# ========== RefSRWKV 参数（Better Start 超分模型） ==========
sr:
  inp_channels: 3
  out_channels: 3
  dim: 32
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 8
  scale: 10

# ========== EnRWKV 参数（增强模型） ==========
enhance:
  inp_channels: 3
  out_channels: 3
  dim: 32
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4

# 数据集参数
data:
  root: "/home/zhy/PROJECT/RefRWKV/RefSR_data/ALL_2"
  mode: "train"
  patch_size: 160
  scale: 10
  augment: true
  augment_ref: true
  ref_aug_strengths: [0.12, 0.12, 0.12, 0.03]
  ref_aug_probs:    [0.5, 0.5, 0.5, 0.5]
  ref_gray_prob: 0.2
  max_samples_train: 10000
  max_samples_val: null
  max_samples_test: null
  batch_size: 8
  num_workers: 2

# 训练参数
train:
  lr_sr: 0.0001
  lr_diff: 0.0005
  lr_enhance: 0.0001
  warmup_epochs: 5
  max_epochs: 200
  accumulate_grad_batches: 4
  precision: "bf16"
  train_sr: true
  train_diff: true
  train_enhance: true
  t_enhance_threshold: 250
  loss_sr_weight: 0.1
  loss_enhance_weight: 0.1

# 输出配置
output:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"